export const localeConfig = {
  en: { prefix: "", htmlLang: "en", short: "EN" },
  "zh-Hant": { prefix: "/zh-hant", htmlLang: "zh-Hant", short: "繁中" },
  "zh-Hans": { prefix: "/zh-hans", htmlLang: "zh-Hans", short: "简中" },
  ja: { prefix: "/ja", htmlLang: "ja", short: "日本語" }
};

export const siteCopy = {
  en: {
    archiveTitle: "Complete Engineering Archive",
    archiveDescription: "All 70 GitHub repositories, plus deployed systems that do not map one-to-one to a repository. Ranked by hiring value and evidence quality, not recency alone.",
    context: "PROJECT ASSET LIBRARY",
    profile: "My LinkedIn profile",
    home: "ANLAN.STORE home",
    skip: "Skip to project inventory",
    search: "Search project names, technologies, and summaries",
    sort: "Sort projects",
    sortValue: "Hiring value & evidence",
    sortUpdated: "Recently updated",
    sortName: "Name A–Z",
    filters: { all: "All", featured: "Featured", applications: "Applications", research: "Research", private: "Private", fork: "Forks", learning: "Learning" },
    inventory: "Project Inventory",
    inventoryIntro: "Every repository appears exactly once. Deployed services are merged with their source repository when they refer to the same project.",
    resultCount: "{count} records visible",
    empty: "No projects match this search and filter.",
    public: "Public",
    private: "Private project",
    original: "Original",
    fork: "Fork / contribution",
    evidence: "Evidence",
    github: "View GitHub repository",
    details: "View project record",
    live: "Open live project",
    locked: "Private repository · access unavailable",
    total: "GitHub repos",
    publicCount: "Public",
    privateCount: "Private",
    caseStudy: "Case study",
    assets: "Engineering assets",
    related: "Related projects",
    backArchive: "Back to complete archive",
    problem: "Problem",
    role: "My role",
    constraints: "Constraints",
    decisions: "Key decisions",
    architecture: "Architecture",
    evidenceSection: "Engineering evidence",
    result: "Result",
    limits: "Limits & next steps",
    metadata: "Project record",
    status: "Status",
    technologies: "Technologies",
    updated: "Repository updated",
    noDate: "Not publicly disclosed",
    sourceRecord: "This project record links the archive facts, available source, live routes, and related evidence without inventing product outcomes.",
    assetNote: "This asset is a public, security-reviewed explanation. Secrets, credentials, private repository content, and internal operating records are excluded.",
    footer: "ANLAN.STORE / DURABLE ENGINEERING EVIDENCE"
  },
  "zh-Hant": {
    archiveTitle: "完整工程資產檔案",
    archiveDescription: "收錄全部 70 個 GitHub 儲存庫，以及未與單一儲存庫一對一對應的線上系統。預設依求職價值與證據品質排序，而非只看更新時間。",
    context: "專案資產庫", profile: "我的 LinkedIn 個人資料", home: "ANLAN.STORE 首頁", skip: "跳至專案清單",
    search: "搜尋專案名稱、技術與摘要", sort: "排序專案", sortValue: "求職價值與證據", sortUpdated: "最近更新", sortName: "名稱 A–Z",
    filters: { all: "全部", featured: "精選", applications: "應用與工具", research: "研究", private: "私人", fork: "Fork", learning: "學習" },
    inventory: "專案清單", inventoryIntro: "每個儲存庫只出現一次；若線上服務與原始碼屬於同一專案，會合併為同一筆記錄。", resultCount: "顯示 {count} 筆", empty: "沒有符合目前搜尋與篩選的專案。",
    public: "公開", private: "私人專案", original: "原創", fork: "Fork / 貢獻", evidence: "證據", github: "查看 GitHub 儲存庫", details: "查看專案記錄", live: "開啟線上專案", locked: "Private repository · access unavailable",
    total: "GitHub 儲存庫", publicCount: "公開", privateCount: "私人", caseStudy: "案例研究", assets: "工程資產", related: "相關專案", backArchive: "返回完整檔案",
    problem: "問題", role: "我的角色", constraints: "限制條件", decisions: "關鍵決策", architecture: "架構", evidenceSection: "工程證據", result: "成果", limits: "限制與下一步",
    metadata: "專案記錄", status: "狀態", technologies: "技術", updated: "儲存庫更新", noDate: "未公開", sourceRecord: "此專案記錄連接清單事實、可用原始碼、線上路由與相關證據，不虛構產品成果。",
    assetNote: "此資產是經安全檢查的公開說明，不包含秘密、憑據、私人儲存庫內容與內部操作記錄。", footer: "ANLAN.STORE / 可持續工程證據"
  },
  "zh-Hans": {
    archiveTitle: "完整工程资产档案",
    archiveDescription: "收录全部 70 个 GitHub 仓库，以及未与单一仓库一对一对应的在线系统。默认按求职价值与证据质量排序，而不是只看更新时间。",
    context: "项目资产库", profile: "我的 LinkedIn 个人资料", home: "ANLAN.STORE 首页", skip: "跳至项目清单",
    search: "搜索项目名称、技术与摘要", sort: "排序项目", sortValue: "求职价值与证据", sortUpdated: "最近更新", sortName: "名称 A–Z",
    filters: { all: "全部", featured: "精选", applications: "应用与工具", research: "研究", private: "私有", fork: "Fork", learning: "学习" },
    inventory: "项目清单", inventoryIntro: "每个仓库只出现一次；如果在线服务与源码属于同一项目，会合并为同一条记录。", resultCount: "显示 {count} 条", empty: "没有符合当前搜索与筛选的项目。",
    public: "公开", private: "私有项目", original: "原创", fork: "Fork / 贡献", evidence: "证据", github: "查看 GitHub 仓库", details: "查看项目记录", live: "打开在线项目", locked: "Private repository · access unavailable",
    total: "GitHub 仓库", publicCount: "公开", privateCount: "私有", caseStudy: "案例研究", assets: "工程资产", related: "相关项目", backArchive: "返回完整档案",
    problem: "问题", role: "我的角色", constraints: "限制条件", decisions: "关键决策", architecture: "架构", evidenceSection: "工程证据", result: "成果", limits: "限制与下一步",
    metadata: "项目记录", status: "状态", technologies: "技术", updated: "仓库更新", noDate: "未公开", sourceRecord: "此项目记录连接清单事实、可用源码、在线路由与相关证据，不虚构产品成果。",
    assetNote: "此资产是经过安全检查的公开说明，不包含秘密、凭据、私有仓库内容与内部操作记录。", footer: "ANLAN.STORE / 可持续工程证据"
  },
  ja: {
    archiveTitle: "完全なエンジニアリング資産目録",
    archiveDescription: "70 件すべての GitHub リポジトリと、単一リポジトリに一対一対応しない公開システムを収録。更新日時だけでなく、採用上の価値と証拠の品質で並べます。",
    context: "プロジェクト資産ライブラリ", profile: "私の LinkedIn プロフィール", home: "ANLAN.STORE ホーム", skip: "プロジェクト目録へ移動",
    search: "プロジェクト名、技術、概要を検索", sort: "プロジェクトを並べ替え", sortValue: "採用価値と証拠", sortUpdated: "最近の更新", sortName: "名前 A–Z",
    filters: { all: "すべて", featured: "注目", applications: "アプリとツール", research: "研究", private: "非公開", fork: "Fork", learning: "学習" },
    inventory: "プロジェクト目録", inventoryIntro: "各リポジトリは一度だけ表示します。公開サービスとソースが同じプロジェクトなら、一つの記録に統合します。", resultCount: "{count} 件を表示", empty: "現在の検索と絞り込みに一致するプロジェクトはありません。",
    public: "公開", private: "非公開プロジェクト", original: "オリジナル", fork: "Fork / 貢献", evidence: "証拠", github: "GitHub リポジトリを見る", details: "プロジェクト記録を見る", live: "公開プロジェクトを開く", locked: "Private repository · access unavailable",
    total: "GitHub リポジトリ", publicCount: "公開", privateCount: "非公開", caseStudy: "ケーススタディ", assets: "エンジニアリング資産", related: "関連プロジェクト", backArchive: "完全な目録へ戻る",
    problem: "課題", role: "担当", constraints: "制約", decisions: "主要な判断", architecture: "アーキテクチャ", evidenceSection: "エンジニアリング証拠", result: "結果", limits: "制限と次の段階",
    metadata: "プロジェクト記録", status: "状態", technologies: "技術", updated: "リポジトリ更新", noDate: "非公開", sourceRecord: "この記録は、架空の成果を作らず、目録の事実、利用可能なソース、公開ルート、関連証拠を結びます。",
    assetNote: "この資産はセキュリティ確認済みの公開説明です。シークレット、認証情報、非公開リポジトリ内容、内部運用記録は含みません。", footer: "ANLAN.STORE / 持続するエンジニアリング証拠"
  }
};

export const assetTitles = {
  architecture: { en: "Architecture Note", "zh-Hant": "架構說明", "zh-Hans": "架构说明", ja: "アーキテクチャノート" },
  "deployment-runbook": { en: "Deployment Runbook", "zh-Hant": "部署 Runbook", "zh-Hans": "部署 Runbook", ja: "デプロイ Runbook" },
  "reliability-adr": { en: "Reliability ADR", "zh-Hant": "可靠性 ADR", "zh-Hans": "可靠性 ADR", ja: "信頼性 ADR" },
  "verification-record": { en: "Verification Record", "zh-Hant": "驗證記錄", "zh-Hans": "验证记录", ja: "検証記録" },
  "practice-guide": { en: "Practice Guide", "zh-Hant": "實作指南", "zh-Hans": "实践指南", ja: "実践ガイド" },
  "privacy-boundaries": { en: "Privacy Boundaries", "zh-Hant": "隱私邊界", "zh-Hans": "隐私边界", ja: "プライバシー境界" }
};
