export const upworkSite = {
  title: "Web development portfolio for small businesses and product teams",
  description: "Practical websites and web applications for small businesses and product teams, backed by clear full-stack engineering evidence.",
  eyebrow: "UPWORK / WEB PRODUCTS & SOFTWARE",
  headline: "Websites and software that help a business move forward.",
  intro: "I help turn a business idea, an existing codebase, or a product that needs improvement into a clear, usable web product.",
  heroNoteTitle: "Good fit for",
  note: "Small businesses and product teams that need an online store, content or community platform, internal tool, dashboard, or focused feature without losing sight of what comes next.",
  heroPrimaryAction: "See what I can build",
  heroSecondaryAction: "See the engineering evidence",
  principleLabel: "A working principle",
  principle: ["Never boastful, never hucksterish;", "Humble in spirit, genuine in products."],
  proof: [
    ["01", "Customer-facing products", "Build practical websites, online stores, content platforms, and focused tools around a real business need."],
    ["02", "Full-stack delivery", "Connect the interface to forms, APIs, data, and the backend behavior the product needs."],
    ["03", "Careful engineering", "Keep validation, errors, maintainability, and future changes visible instead of hiding problems behind a polished screen."]
  ],
  methodTitle: "How a project moves forward",
  methodLabel: "How I work",
  method: [
    ["Understand", "Start with the business goal, the people using the product, and the smallest useful result."],
    ["Build", "Turn the idea into a focused website, feature, or application flow with clear states and useful feedback."],
    ["Check", "Test the important paths, handle bad input and failure states, and make the result easy to review."],
    ["Hand over", "Leave behind a working result, clear evidence, and an honest view of what should happen next."],
  ],
  boundaryTitle: "Clear examples, honest boundaries",
  boundary: "The examples below show how I approach product work and engineering decisions. The demos are self-contained browser experiences: they do not call an AI provider, expose private customer material, or pretend to be commercial production systems. PulseBoard is a production-shaped portfolio project, and its reliability evidence is presented with that boundary intact.",
  contactTitle: "Have an idea, website, or existing codebase to improve?",
  contactText: "Start with the kind of work you need, then use the case study or the broader hire page to see the engineering evidence and working boundaries behind it.",
  contactLabel: "Start a conversation",
  contactAction: "Review the evidence",
  portfolioLabel: "Examples of the work",
  portfolioTitle: "What I can help you build or improve",
  portfolioIntro: "The examples below show three ways I can contribute: building a focused product feature, improving existing code, and making the backend easier to trust.",
};

export const upworkPortfolio = [
  {
    slug: "feature-delivery",
    index: "01",
    title: "Build a focused product feature",
    short: "Turn one important business request into a usable, tested product feature.",
    tile: {
      src: "/upwork/assets/tile-feature-delivery.png",
      alt: "Screenshot of the release planner demo in a browser window, with callouts for describing a feature, live queue statistics, and status filters.",
      label: "Release planner UI",
      width: 660,
      height: 392,
    },
    concept: {
      src: "/upwork/assets/concept-feature-delivery.jpg",
      alt: "Concept illustration of work cards moving through a delivery board toward a launch.",
      caption: "Concept illustration: a slice moving from idea to shipped.",
      width: 1536,
      height: 952,
    },
    tags: ["React / TypeScript", "Node boundary", "Forms and state", "PostgreSQL-shaped model"],
    problem: "A feature request is easy to describe and easy to under-specify. The useful work is making the data shape, validation, loading state, API failure, and hand-off boundary explicit without turning a small feature into a rewrite.",
    approach: "The case study uses a release-planning slice: a typed-looking form creates a feature record, validates required fields, and lets a reviewer scan status and priority. The browser demo is a representative implementation pattern, not a claim that this exact screen is a deployed client product.",
    proof: "The interactive flow makes the acceptance surface inspectable: invalid input stays local, valid input becomes a visible record, and filters preserve a predictable review path.",
    limits: "The demo uses an in-memory browser data layer. It does not prove a remote API, real database writes, or a production deployment. Those would be the next verification steps in a client repository.",
    delivery: ["Requirement slice", "State model", "Validation and error path", "Reviewable hand-off"],
    demoType: "feature",
    demoLabel: "Representative browser demo",
    demoTitle: "Release planner: add and review a feature slice",
    demoNote: "Browser-only example. Records live in this page and reset on refresh.",
    heroVisual: {
      src: "/upwork/assets/planner-annotated.png",
      alt: "Annotated screenshot of the release planner demo inside a browser window: the add-feature form, live queue statistics, status filters, and inspectable feature records, each with a numbered callout.",
      label: "Release planner / annotated tour",
      width: 1180,
      height: 642,
    },
    productVisuals: [
      {
        src: "/upwork/assets/feature-planner-demo.png",
        alt: "Screenshot of the release planner demo with a freshly added feature record and the confirmation message visible.",
        label: "Demo state / after adding a record",
        caption: "A valid submission becomes a visible record with owner and priority.",
        width: 1120,
        height: 630,
      },
      {
        src: "/upwork/assets/feature-error-state.png",
        alt: "Screenshot of the release planner demo with a visible validation error under the form while the existing feature records remain listed.",
        label: "UI states / validation error path",
        caption: "Invalid input stays local with a readable error; the list state is preserved.",
        width: 1120,
        height: 630,
      },
    ],
    diagrams: [
      {
        src: "/upwork/assets/feature-flow.svg",
        alt: "Flow diagram of the feature delivery method: requirement slice, visible status model, validation with readable errors, and a review hand-off a reviewer can inspect.",
        label: "Feature delivery flow",
        caption: "Requirement slice to status model to validation to review hand-off.",
        width: 1200,
        height: 520,
      },
    ],
  },
  {
    slug: "ai-code-rescue",
    index: "02",
    title: "Repair and improve existing code",
    short: "Make inherited or AI-assisted code safer, clearer, and easier to extend.",
    tile: {
      src: "/upwork/assets/tile-code-rescue.png",
      alt: "Screenshot of the code repair desk demo in a browser window, with callouts for picking a defect sample, comparing before and after code, and running local checks.",
      label: "Before / after code review",
      width: 660,
      height: 392,
    },
    concept: {
      src: "/upwork/assets/concept-code-rescue.jpg",
      alt: "Concept illustration of a magnifying glass and wrench repairing a cracked code block until a check badge appears.",
      caption: "Concept illustration: inspect, repair, verify.",
      width: 1536,
      height: 952,
    },
    tags: ["Code review", "Async correctness", "Input boundaries", "Deterministic checks"],
    problem: "AI-assisted code can be fast to produce and expensive to trust. The risk is rarely the syntax alone: it is the missing boundary around inputs, stale async state, authorization assumptions, duplicated logic, or an error path that disappears into a catch block.",
    approach: "I have worked with AI-generated and AI-assisted code by reviewing it, fixing defects, and refactoring the result into code that can be reasoned about. This portfolio demo uses representative samples so the method is public without exposing a client codebase or inventing a client outcome.",
    proof: "Each sample has a concrete defect, a repaired version, and deterministic checks that explain why the repair matters. The viewer can switch samples and run the checks without an API key.",
    limits: "The samples are intentionally small teaching cases. They demonstrate review judgment, not a measured customer result, model benchmark, or claim about every generated codebase.",
    delivery: ["Defect isolation", "Before / after diff", "Targeted verification", "Conservative refactor"],
    demoType: "rescue",
    demoLabel: "Representative code-review demo",
    demoTitle: "Repair desk: inspect a defect and run the checks",
    demoNote: "Deterministic local samples. No model call or private code is involved.",
    heroVisual: {
      src: "/upwork/assets/rescue-annotated.png",
      alt: "Before and after code panes side by side with a repaired arrow between them and three green pass badges: request token per load, body read before the guard, stale response blocked.",
      label: "Before / after repair",
      width: 1180,
      height: 332,
    },
    productVisuals: [
      {
        src: "/upwork/assets/rescue-repair-demo.png",
        alt: "Screenshot of the code repair desk demo showing the repaired async state guard sample and its deterministic checks passing.",
        label: "Repair desk / after state with checks passing",
        caption: "The interactive demo's repaired state: real code text, checks run locally.",
        width: 1120,
        height: 630,
      },
    ],
    diagrams: [
      {
        src: "/upwork/assets/rescue-risk-map.svg",
        alt: "Diagram of three recurring risks in generated code: a missing async state guard, a caller-controlled input boundary, and a validation error path hidden by a catch block, each with its repair.",
        label: "Three risk points",
        caption: "Async state, input boundary, validation error: the risks reviewed first, with the repair pattern for each.",
        width: 1200,
        height: 620,
      },
    ],
  },
  {
    slug: "backend-reliability",
    index: "03",
    title: "Strengthen the backend and reliability",
    short: "Make APIs, data, background work, and recovery paths easier to trust.",
    tile: {
      src: "/upwork/assets/tile-backend-reliability.png",
      alt: "Screenshot of the recovery runbook simulation in a browser window, with callouts for the four recovery gates, the visible pass state, and the no-external-systems boundary.",
      label: "Recovery architecture / runbook",
      width: 660,
      height: 392,
    },
    concept: {
      src: "/upwork/assets/concept-reliability.jpg",
      alt: "Concept illustration of servers, a database cylinder, and a job queue under a protective dome with a heartbeat line.",
      caption: "Concept illustration: the system under observation and protection.",
      width: 1536,
      height: 952,
    },
    tags: ["Hono API", "PostgreSQL / Prisma", "Redis / BullMQ", "Health and recovery"],
    problem: "A backend is more than a happy-path endpoint. Reviewers need to see authentication boundaries, durable state, worker behavior, readiness signals, and what a recovery or rollback rehearsal can actually prove.",
    approach: "PulseBoard is the real evidence anchor: a production-shaped portfolio project with a Hono API, PostgreSQL and Prisma, Redis and BullMQ, API-key boundaries, OpenAPI, liveness/readiness, worker recovery, and local backup/restore and rollback rehearsals.",
    proof: "The demo below is an explicit simulation of an operational runbook. It walks through health checks, queue retry, a restore gate, and rollback verification so the distinction between a documented procedure and a live production claim stays visible.",
    limits: "The simulation is not a live incident system and does not establish production traffic, SLA, RPO/RTO, or a successful remote deployment. AWS remains plan-only in the current evidence boundary.",
    delivery: ["API contract", "Durable state", "Async recovery", "Runbook evidence"],
    demoType: "reliability",
    demoLabel: "Explicit reliability simulation",
    demoTitle: "Recovery runbook: step through a controlled simulation",
    demoNote: "Simulation only. It does not touch a database, queue, cloud account, or production service.",
    heroVisual: {
      src: "/upwork/assets/recovery-visual.png",
      alt: "Plain-language backend overview with icons: web app, API, database, job queue, and a recovery shield, plus a note that the runbook on this page is a browser-only simulation and AWS stays plan-only.",
      label: "Backend overview / plain-language",
      width: 1180,
      height: 352,
    },
    productVisuals: [
      {
        src: "/upwork/assets/reliability-simulation-demo.png",
        alt: "Screenshot of the recovery runbook simulation with all four gates in the passed state and the completion message visible.",
        label: "Simulation state / all gates passed",
        caption: "The simulation's completed state, as rendered by the interactive demo on this page.",
        width: 1120,
        height: 630,
      },
    ],
    diagrams: [
      {
        src: "/upwork/assets/reliability-architecture.svg",
        alt: "Architecture diagram separating PulseBoard repository evidence (Hono API, PostgreSQL with Prisma, Redis with BullMQ, worker, health gates, local rehearsals) from the browser-only recovery runbook simulation on this page; AWS stays plan-only.",
        label: "Evidence vs simulation zones",
        caption: "Zone A is repository evidence; Zone B is this page's browser-only simulation.",
        width: 1200,
        height: 700,
      },
      {
        src: "/upwork/assets/reliability-runbook.svg",
        alt: "Timeline of the recovery runbook: health gate, queue retry, restore gate, and rollback check, each with its pass condition, labeled as an in-page simulation.",
        label: "Recovery runbook timeline",
        caption: "Four gates, each with an explicit pass condition before the next step runs.",
        width: 1200,
        height: 440,
      },
    ],
  },
];
